package cg.binu.input;

import java.util.ArrayList;
import java.util.List;

/**
 * Creates a card given a card number.
 */
public class CardFactory {
    private static List<Card> cards = new ArrayList<>();

    static {
        cards.add(new Card(1, "Slimer", CardType.CREATURES, 1, 2, 1, "------", 1, 0, 0));
        cards.add(new Card(2, "Scuttler", CardType.CREATURES, 1, 1, 2, "------", 0, -1, 0));
        cards.add(new Card(3, "Beavrat", CardType.CREATURES, 1, 2, 2, "------", 0, 0, 0));
        cards.add(new Card(4, "PlatedToad", CardType.CREATURES, 2, 1, 5, "------", 0, 0, 0));
        cards.add(new Card(5, "GrimeGnasher", CardType.CREATURES, 2, 4, 1, "------", 0, 0, 0));
        cards.add(new Card(6, "Murgling", CardType.CREATURES, 2, 3, 2, "------", 0, 0, 0));
        cards.add(new Card(7, "RootkinSapling", CardType.CREATURES, 2, 2, 2, "-----W", 0, 0, 0));
        cards.add(new Card(8, "Psyshroom", CardType.CREATURES, 2, 2, 3, "------", 0, 0, 0));
        cards.add(new Card(9, "CorruptedBeavrat", CardType.CREATURES, 3, 3, 4, "------", 0, 0, 0));
        cards.add(new Card(10, "CarnivorousBush", CardType.CREATURES, 3, 3, 1, "--D---", 0, 0, 0));
        cards.add(new Card(11, "Snowsaur", CardType.CREATURES, 3, 5, 2, "------", 0, 0, 0));
        cards.add(new Card(12, "Woodshroom", CardType.CREATURES, 3, 2, 5, "------", 0, 0, 0));
        cards.add(new Card(13, "SwampTerror", CardType.CREATURES, 4, 5, 3, "------", 1, -1, 0));
        cards.add(new Card(14, "FangedLunger", CardType.CREATURES, 4, 9, 1, "------", 0, 0, 0));
        cards.add(new Card(15, "PouncingFlailmouth", CardType.CREATURES, 4, 4, 5, "------", 0, 0, 0));
        cards.add(new Card(16, "WranglerFish", CardType.CREATURES, 4, 6, 2, "------", 0, 0, 0));
        cards.add(new Card(17, "AshWalker", CardType.CREATURES, 4, 4, 5, "------", 0, 0, 0));
        cards.add(new Card(18, "AcidGolem", CardType.CREATURES, 4, 7, 4, "------", 0, 0, 0));
        cards.add(new Card(19, "Foulbeast", CardType.CREATURES, 5, 5, 6, "------", 0, 0, 0));
        cards.add(new Card(20, "HedgeDemon", CardType.CREATURES, 5, 8, 2, "------", 0, 0, 0));
        cards.add(new Card(21, "CrestedScuttler", CardType.CREATURES, 5, 6, 5, "------", 0, 0, 0));
        cards.add(new Card(22, "Sigbovak", CardType.CREATURES, 6, 7, 5, "------", 0, 0, 0));
        cards.add(new Card(23, "TitanCaveHog", CardType.CREATURES, 7, 8, 8, "------", 0, 0, 0));
        cards.add(new Card(24, "ExplodingSkitterbug", CardType.CREATURES, 1, 1, 1, "------", 0, -1, 0));
        cards.add(new Card(25, "SpineyChompleaf", CardType.CREATURES, 2, 3, 1, "------", -2, -2, 0));
        cards.add(new Card(26, "RazorCrab", CardType.CREATURES, 2, 3, 2, "------", 0, -1, 0));
        cards.add(new Card(27, "NutGatherer", CardType.CREATURES, 2, 2, 2, "------", 2, 0, 0));
        cards.add(new Card(28, "InfestedToad", CardType.CREATURES, 2, 1, 2, "------", 0, 0, 1));
        cards.add(new Card(29, "SteelplumeNestling", CardType.CREATURES, 2, 2, 1, "------", 0, 0, 1));
        cards.add(new Card(30, "VenomousBogHopper", CardType.CREATURES, 3, 4, 2, "------", 0, -2, 0));
        cards.add(new Card(31, "WoodlandHunter", CardType.CREATURES, 3, 3, 1, "------", 0, -1, 0));
        cards.add(new Card(32, "Sandsplat", CardType.CREATURES, 3, 3, 2, "------", 0, 0, 1));
        cards.add(new Card(33, "Chameleskulk", CardType.CREATURES, 4, 4, 3, "------", 0, 0, 1));
        cards.add(new Card(34, "EldritchCyclops", CardType.CREATURES, 5, 3, 5, "------", 0, 0, 1));
        cards.add(new Card(35, "Snail-eyedHulker", CardType.CREATURES, 6, 5, 2, "B-----", 0, 0, 1));
        cards.add(new Card(36, "PossessedSkull", CardType.CREATURES, 6, 4, 4, "------", 0, 0, 2));
        cards.add(new Card(37, "EldritchMulticlops", CardType.CREATURES, 6, 5, 7, "------", 0, 0, 1));
        cards.add(new Card(38, "Imp", CardType.CREATURES, 1, 1, 3, "--D---", 0, 0, 0));
        cards.add(new Card(39, "VoraciousImp", CardType.CREATURES, 1, 2, 1, "--D---", 0, 0, 0));
        cards.add(new Card(40, "RockGobbler", CardType.CREATURES, 3, 2, 3, "--DG--", 0, 0, 0));
        cards.add(new Card(41, "BlizzardDemon", CardType.CREATURES, 3, 2, 2, "-CD---", 0, 0, 0));
        cards.add(new Card(42, "FlyingLeech", CardType.CREATURES, 4, 4, 2, "--D---", 0, 0, 0));
        cards.add(new Card(43, "ScreechingNightmare", CardType.CREATURES, 6, 5, 5, "--D---", 0, 0, 0));
        cards.add(new Card(44, "Deathstalker", CardType.CREATURES, 6, 3, 7, "--D-L-", 0, 0, 0));
        cards.add(new Card(45, "NightHowler", CardType.CREATURES, 6, 6, 5, "B-D---", -3, 0, 0));
        cards.add(new Card(46, "SoulDevourer", CardType.CREATURES, 9, 7, 7, "--D---", 0, 0, 0));
        cards.add(new Card(47, "Gnipper", CardType.CREATURES, 2, 1, 5, "--D---", 0, 0, 0));
        cards.add(new Card(48, "VenomHedgehog", CardType.CREATURES, 1, 1, 1, "----L-", 0, 0, 0));
        cards.add(new Card(49, "ShinyProwler", CardType.CREATURES, 2, 1, 2, "---GL-", 0, 0, 0));
        cards.add(new Card(50, "PuffBiter", CardType.CREATURES, 3, 3, 2, "----L-", 0, 0, 0));
        cards.add(new Card(51, "EliteBilespitter", CardType.CREATURES, 4, 3, 5, "----L-", 0, 0, 0));
        cards.add(new Card(52, "Bilespitter", CardType.CREATURES, 4, 2, 4, "----L-", 0, 0, 0));
        cards.add(new Card(53, "PossessedAbomination", CardType.CREATURES, 4, 1, 1, "-C--L-", 0, 0, 0));
        cards.add(new Card(54, "ShadowBiter", CardType.CREATURES, 3, 2, 2, "----L-", 0, 0, 0));
        cards.add(new Card(55, "HermitSlime", CardType.CREATURES, 2, 0, 5, "---G--", 0, 0, 0));
        cards.add(new Card(56, "GiantLouse", CardType.CREATURES, 4, 2, 7, "------", 0, 0, 0));
        cards.add(new Card(57, "Dream-Eater", CardType.CREATURES, 4, 1, 8, "------", 0, 0, 0));
        cards.add(new Card(58, "DarkscalePredator", CardType.CREATURES, 6, 5, 6, "B-----", 0, 0, 0));
        cards.add(new Card(59, "SeaGhost", CardType.CREATURES, 7, 7, 7, "------", 1, -1, 0));
        cards.add(new Card(60, "GritsuckTroll", CardType.CREATURES, 7, 4, 8, "------", 0, 0, 0));
        cards.add(new Card(61, "AlphaTroll", CardType.CREATURES, 9, 10, 10, "------", 0, 0, 0));
        cards.add(new Card(62, "MutantTroll", CardType.CREATURES, 12, 12, 12, "B--G--", 0, 0, 0));
        cards.add(new Card(63, "RootkinDrone", CardType.CREATURES, 2, 0, 4, "---G-W", 0, 0, 0));
        cards.add(new Card(64, "CoppershellTortoise", CardType.CREATURES, 2, 1, 1, "---G-W", 0, 0, 0));
        cards.add(new Card(65, "SteelplumeDefender", CardType.CREATURES, 2, 2, 2, "-----W", 0, 0, 0));
        cards.add(new Card(66, "StaringWickerbeast", CardType.CREATURES, 5, 5, 1, "-----W", 0, 0, 0));
        cards.add(new Card(67, "FlailingHammerhead", CardType.CREATURES, 6, 5, 5, "-----W", 0, -2, 0));
        cards.add(new Card(68, "GiantSquid", CardType.CREATURES, 6, 7, 5, "-----W", 0, 0, 0));
        cards.add(new Card(69, "ChargingBoarhound", CardType.CREATURES, 3, 4, 4, "B-----", 0, 0, 0));
        cards.add(new Card(70, "Murglord", CardType.CREATURES, 4, 6, 3, "B-----", 0, 0, 0));
        cards.add(new Card(71, "FlyingMurgling", CardType.CREATURES, 4, 3, 2, "BC----", 0, 0, 0));
        cards.add(new Card(72, "ShufflingNightmare", CardType.CREATURES, 4, 5, 3, "B-----", 0, 0, 0));
        cards.add(new Card(73, "BogBounder", CardType.CREATURES, 4, 4, 4, "B-----", 4, 0, 0));
        cards.add(new Card(74, "Crusher", CardType.CREATURES, 5, 5, 4, "B--G--", 0, 0, 0));
        cards.add(new Card(75, "TitanProwler", CardType.CREATURES, 5, 6, 5, "B-----", 0, 0, 0));
        cards.add(new Card(76, "CrestedChomper", CardType.CREATURES, 6, 5, 5, "B-D---", 0, 0, 0));
        cards.add(new Card(77, "LumberingGiant", CardType.CREATURES, 7, 7, 7, "B-----", 0, 0, 0));
        cards.add(new Card(78, "Shambler", CardType.CREATURES, 8, 5, 5, "B-----", 0, -5, 0));
        cards.add(new Card(79, "ScarletColossus", CardType.CREATURES, 8, 8, 8, "B-----", 0, 0, 0));
        cards.add(new Card(80, "CorpseGuzzler", CardType.CREATURES, 8, 8, 8, "B--G--", 0, 0, 1));
        cards.add(new Card(81, "FlyingCorpseGuzzler", CardType.CREATURES, 9, 6, 6, "BC----", 0, 0, 0));
        cards.add(new Card(82, "SlitheringNightmare", CardType.CREATURES, 7, 5, 5, "B-D--W", 0, 0, 0));
        cards.add(new Card(83, "RestlessOwl", CardType.CREATURES, 0, 1, 1, "-C----", 0, 0, 0));
        cards.add(new Card(84, "FighterTick", CardType.CREATURES, 2, 1, 1, "-CD--W", 0, 0, 0));
        cards.add(new Card(85, "HeartlessCrow", CardType.CREATURES, 3, 2, 3, "-C----", 0, 0, 0));
        cards.add(new Card(86, "CrazedNose-pincher", CardType.CREATURES, 3, 1, 5, "-C----", 0, 0, 0));
        cards.add(new Card(87, "BloatDemon", CardType.CREATURES, 4, 2, 5, "-C-G--", 0, 0, 0));
        cards.add(new Card(88, "AbyssNightmare", CardType.CREATURES, 5, 4, 4, "-C----", 0, 0, 0));
        cards.add(new Card(89, "Boombeak", CardType.CREATURES, 5, 4, 1, "-C----", 2, 0, 0));
        cards.add(new Card(90, "EldritchSwooper", CardType.CREATURES, 8, 5, 5, "-C----", 0, 0, 0));
        cards.add(new Card(91, "Flumpy", CardType.CREATURES, 0, 1, 2, "---G--", 0, 1, 0));
        cards.add(new Card(92, "Wurm", CardType.CREATURES, 1, 0, 1, "---G--", 2, 0, 0));
        cards.add(new Card(93, "Spinekid", CardType.CREATURES, 1, 2, 1, "---G--", 0, 0, 0));
        cards.add(new Card(94, "RootkinDefender", CardType.CREATURES, 2, 1, 4, "---G--", 0, 0, 0));
        cards.add(new Card(95, "Wildum", CardType.CREATURES, 2, 2, 3, "---G--", 0, 0, 0));
        cards.add(new Card(96, "PrairieProtector", CardType.CREATURES, 2, 3, 2, "---G--", 0, 0, 0));
        cards.add(new Card(97, "Turta", CardType.CREATURES, 3, 3, 3, "---G--", 0, 0, 0));
        cards.add(new Card(98, "LillyHopper", CardType.CREATURES, 3, 2, 4, "---G--", 0, 0, 0));
        cards.add(new Card(99, "CaveCrab", CardType.CREATURES, 3, 2, 5, "---G--", 0, 0, 0));
        cards.add(new Card(100, "Stalagopod", CardType.CREATURES, 3, 1, 6, "---G--", 0, 0, 0));
        cards.add(new Card(101, "Engulfer", CardType.CREATURES, 4, 3, 4, "---G--", 0, 0, 0));
        cards.add(new Card(102, "MoleDemon", CardType.CREATURES, 4, 3, 3, "---G--", 0, -1, 0));
        cards.add(new Card(103, "MutatingRootkin", CardType.CREATURES, 4, 3, 6, "---G--", 0, 0, 0));
        cards.add(new Card(104, "DeepwaterShellcrab", CardType.CREATURES, 4, 4, 4, "---G--", 0, 0, 0));
        cards.add(new Card(105, "KingShellcrab", CardType.CREATURES, 5, 4, 6, "---G--", 0, 0, 0));
        cards.add(new Card(106, "Far-reachingNightmare", CardType.CREATURES, 5, 5, 5, "---G--", 0, 0, 0));
        cards.add(new Card(107, "WorkerShellcrab", CardType.CREATURES, 5, 3, 3, "---G--", 3, 0, 0));
        cards.add(new Card(108, "RootkinElder", CardType.CREATURES, 5, 2, 6, "---G--", 0, 0, 0));
        cards.add(new Card(109, "ElderEngulfer", CardType.CREATURES, 5, 5, 6, "------", 0, 0, 0));
        cards.add(new Card(110, "Gargoyle", CardType.CREATURES, 5, 0, 9, "---G--", 0, 0, 0));
        cards.add(new Card(111, "TurtaKnight", CardType.CREATURES, 6, 6, 6, "---G--", 0, 0, 0));
        cards.add(new Card(112, "RootkinLeader", CardType.CREATURES, 6, 4, 7, "---G--", 0, 0, 0));
        cards.add(new Card(113, "TamedBilespitter", CardType.CREATURES, 6, 2, 4, "---G--", 4, 0, 0));
        cards.add(new Card(114, "Gargantua", CardType.CREATURES, 7, 7, 7, "---G--", 0, 0, 0));
        cards.add(new Card(115, "RootkinWarchief", CardType.CREATURES, 8, 5, 5, "---G-W", 0, 0, 0));
        cards.add(new Card(116, "EmperorNightmare", CardType.CREATURES, 12, 8, 8, "BCDGLW", 0, 0, 0));
        cards.add(new Card(117, "Protein", CardType.ITEM_GREEN, 1, 1, 1, "B-----", 0, 0, 0));
        cards.add(new Card(118, "RoyalHelm", CardType.ITEM_GREEN, 0, 0, 3, "------", 0, 0, 0));
        cards.add(new Card(119, "SerratedShield", CardType.ITEM_GREEN, 1, 1, 2, "------", 0, 0, 0));
        cards.add(new Card(120, "Venomfruit", CardType.ITEM_GREEN, 2, 1, 0, "----L-", 0, 0, 0));
        cards.add(new Card(121, "EnchantedHat", CardType.ITEM_GREEN, 2, 0, 3, "------", 0, 0, 1));
        cards.add(new Card(122, "BolsteringBread", CardType.ITEM_GREEN, 2, 1, 3, "---G--", 0, 0, 0));
        cards.add(new Card(123, "Wristguards", CardType.ITEM_GREEN, 2, 4, 0, "------", 0, 0, 0));
        cards.add(new Card(124, "BloodGrapes", CardType.ITEM_GREEN, 3, 2, 1, "--D---", 0, 0, 0));
        cards.add(new Card(125, "HealthyVeggies", CardType.ITEM_GREEN, 3, 1, 4, "------", 0, 0, 0));
        cards.add(new Card(126, "HeavyShield", CardType.ITEM_GREEN, 3, 2, 3, "------", 0, 0, 0));
        cards.add(new Card(127, "ImperialHelm", CardType.ITEM_GREEN, 3, 0, 6, "------", 0, 0, 0));
        cards.add(new Card(128, "EnchantedCloth", CardType.ITEM_GREEN, 4, 4, 3, "------", 0, 0, 0));
        cards.add(new Card(129, "EnchantedLeather", CardType.ITEM_GREEN, 4, 2, 5, "------", 0, 0, 0));
        cards.add(new Card(130, "HelmofRemedy", CardType.ITEM_GREEN, 4, 0, 6, "------", 4, 0, 0));
        cards.add(new Card(131, "HeavyGauntlet", CardType.ITEM_GREEN, 4, 4, 1, "------", 0, 0, 0));
        cards.add(new Card(132, "HighProtein", CardType.ITEM_GREEN, 5, 3, 3, "B-----", 0, 0, 0));
        cards.add(new Card(133, "PieofPower", CardType.ITEM_GREEN, 5, 4, 0, "-----W", 0, 0, 0));
        cards.add(new Card(134, "LightTheWay", CardType.ITEM_GREEN, 4, 2, 2, "------", 0, 0, 1));
        cards.add(new Card(135, "ImperialArmour", CardType.ITEM_GREEN, 6, 5, 5, "------", 0, 0, 0));
        cards.add(new Card(136, "Buckler", CardType.ITEM_GREEN, 0, 1, 1, "------", 0, 0, 0));
        cards.add(new Card(137, "Ward", CardType.ITEM_GREEN, 2, 0, 0, "-----W", 0, 0, 0));
        cards.add(new Card(138, "GrowHorns", CardType.ITEM_GREEN, 2, 0, 0, "---G--", 0, 0, 1));
        cards.add(new Card(139, "GrowStingers", CardType.ITEM_GREEN, 4, 0, 0, "----LW", 0, 0, 0));
        cards.add(new Card(140, "GrowWings", CardType.ITEM_GREEN, 2, 0, 0, "-C----", 0, 0, 0));
        cards.add(new Card(141, "ThrowingKnife", CardType.ITEM_RED, 0, -1, -1, "------", 0, 0, 0));
        cards.add(new Card(142, "StaffofSuppression", CardType.ITEM_RED, 0, 0, 0, "BCDGLW", 0, 0, 0));
        cards.add(new Card(143, "PierceArmour", CardType.ITEM_RED, 0, 0, 0, "---G--", 0, 0, 0));
        cards.add(new Card(144, "RuneAxe", CardType.ITEM_RED, 1, 0, -2, "------", 0, 0, 0));
        cards.add(new Card(145, "CursedSword", CardType.ITEM_RED, 3, -2, -2, "------", 0, 0, 0));
        cards.add(new Card(146, "CursedScimitar", CardType.ITEM_RED, 4, -2, -2, "------", 0, -2, 0));
        cards.add(new Card(147, "QuickShot", CardType.ITEM_RED, 2, 0, -1, "------", 0, 0, 1));
        cards.add(new Card(148, "HelmCrusher", CardType.ITEM_RED, 2, 0, -2, "BCDGLW", 0, 0, 0));
        cards.add(new Card(149, "RootkinRitual", CardType.ITEM_RED, 3, 0, 0, "BCDGLW", 0, 0, 1));
        cards.add(new Card(150, "ThrowingAxe", CardType.ITEM_RED, 2, 0, -3, "------", 0, 0, 0));
        cards.add(new Card(151, "Decimate", CardType.ITEM_RED, 5, 0, -99, "BCDGLW", 0, 0, 0));
        cards.add(new Card(152, "MightyThrowingAxe", CardType.ITEM_RED, 7, 0, -7, "------", 0, 0, 1));
        cards.add(new Card(153, "HealingPotion", CardType.ITEM_BLUE, 2, 0, 0, "------", 5, 0, 0));
        cards.add(new Card(154, "Poison", CardType.ITEM_BLUE, 2, 0, 0, "------", 0, -2, 1));
        cards.add(new Card(155, "ScrollofFirebolt", CardType.ITEM_BLUE, 3, 0, -3, "------", 0, -1, 0));
        cards.add(new Card(156, "MajorLifeStealPotion", CardType.ITEM_BLUE, 3, 0, 0, "------", 3, -3, 0));
        cards.add(new Card(157, "LifeSapDrop", CardType.ITEM_BLUE, 3, 0, -1, "------", 1, 0, 1));
        cards.add(new Card(158, "TomeofThunder", CardType.ITEM_BLUE, 3, 0, -4, "------", 0, 0, 0));
        cards.add(new Card(159, "VialofSoulDrain", CardType.ITEM_BLUE, 4, 0, -3, "------", 3, 0, 0));
        cards.add(new Card(160, "MinorLifeStealPotion", CardType.ITEM_BLUE, 2, 0, 0, "------", 2, -2, 0));
    }

    public static Card get(int id) {
        if (id > 0 && id <= 160) {
            return cards.get(id - 1);
        }

        throw new UnsupportedOperationException("Card with this id does not exist.");
    }
}
