/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'binu' at '19/11/18 06:47' with Gradle 2.13
 *
 * @author binu, @date 19/11/18 06:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
